name: voicemock
description: VoiceMock AI Interview Coach
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audio_session: ^0.2.2
  bloc: ^9.0.1
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  record: ^6.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash/splash_logo.png"
  android: true
  ios: true
